# Wallust Kitty colors
foreground #FFE6D3
background #09001A

selection_foreground #FFE6D3
selection_background #09001A

cursor #13A6DB
cursor_text_color #09001A

url_color #13A6DB

color0  #09001A
color1  #5A9C0C
color2  #0F9613
color3  #13B99C
color4  #13A6DB
color5  #1298FE
color6  #1298FE
color7  #F6D3B8
color8  #AC9380
color9  #5A9C0C
color10 #0F9613
color11 #13B99C
color12 #13A6DB
color13 #1298FE
color14 #1298FE
color15 #F6D3B8
