# Wallust Kitty colors
foreground #ECECFB
background #07050B

selection_foreground #ECECFB
selection_background #3D3C40

cursor #6861AF
cursor_text_color #07050B

url_color #6861AF

color0  #3D3C40
color1  #918CF4
color2  #918CF4
color3  #7C77D1
color4  #6861AF
color5  #585192
color6  #5C538B
color7  #DCDBF1
color8  #9A99A9
color9  #918CF4
color10 #918CF4
color11 #7C77D1
color12 #6861AF
color13 #585192
color14 #5C538B
color15 #DCDBF1
