# Hyprlock Config
#
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

source = colors.conf

$font = JetBrainsMono Nerd Font Mono

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $primary $primary_fixed_dim 45deg
    check_color = $tertiary $tertiary_fixed_dim 120deg
    fail_color = $error $error_container 40deg

    font_color = $on_surface
    fade_on_empty = false
    rounding = 10

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 30
    font_family = $font
    color = $primary

    position = -30, 65
    halign = right
    valign = bottom
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 20
    font_family = $font
    color = $on_surface_variant

    position = -30, 30
    halign = right
    valign = bottom
}

# SPOTIFY
label {
    monitor = 
    text = cmd[update:1000] ~/.config/hypr/scripts/nowplaying.sh
    font_size = 20
    font_family = $font
    color = $tertiary

    position = 30, 120
    halign = left
    valign = bottom
}

# Media Progress
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/mediaprogress.sh
    font_size = 12
    font_family = $font
    color = $on_surface_variant

    position = 30, 80
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:3000] ~/.config/hypr/scripts/mediaicon.sh prev
    font_size = 24
    font_family = $font
    color = $on_surface
    onclick = ~/.config/hypr/scripts/mediactl.sh previous

    position = 30, 30
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:3000] ~/.config/hypr/scripts/mediaicon.sh toggle
    font_size = 24
    font_family = $font
    color = $primary
    onclick = ~/.config/hypr/scripts/mediactl.sh play-pause

    position = 180, 30
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:3000] ~/.config/hypr/scripts/mediaicon.sh next
    font_size = 24
    font_family = $font
    color = $on_surface
    onclick = ~/.config/hypr/scripts/mediactl.sh next

    position = 330, 30
    halign = left
    valign = bottom
}

# SYSTEM INFO
label {
    monitor = 
    text = cmd[update:10000] ~/.config/hypr/scripts/sysinfo.sh
    font_size = 14
    font_family = $font
    color = $on_surface

    position = -30, -30
    halign = right
    valign = top
}

# Notifs
label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/scripts/notifcount.sh
    font_size = 14
    font_family = $font
    color = $tertiary

    position = 30, -30
    halign = left
    valign = top
}
