-- Generated by matugen from ~/.config/matugen/templates/hyprland-colors.lua
-- Edits here are overwritten on the next matugen run.

return {
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}
